import {
  RiUserStarLine,
  RiMoneyDollarCircleLine,
  RiMapPinLine,
} from "react-icons/ri";
import { FaTripadvisor } from "react-icons/fa";

export const PackageData = [
  {
    id: 1,
    region: "Everest Region",
    country: "Nepal",
    duration: "13 days",
    title: "Everest Base Camp Trek - 13 Days",
    difficulty: "Moderate",
    altitude: "5555",
    price: "1,499",
    reviews: 14,
    bannerMessage: "Booking Open for 2025",
    image: "/Images/package/everest-base-camp-trek.jpeg",
  },
  {
    id: 2,
    region: "Annapurna Region",
    country: "Nepal",
    duration: "11 days",
    title: "Annapurna Base Camp Trek - 11 Days",
    difficulty: "Moderate",
    altitude: "4130",
    price: "800",
    reviews: 14,
    bannerMessage: "Booking Open for 2025",
    image: "/Images/package/everest-base-camp-trek.jpeg",
  },
  {
    id: 3,
    region: "Annapurna Region",
    country: "Nepal",
    duration: "7 days",
    title: "Mardi Himal Trek - 7 Days",
    difficulty: "Moderate",
    altitude: "5545",
    price: "500",
    reviews: 14,
    bannerMessage: "Booking Open for 2025",
    image: "/Images/package/everest-base-camp-trek.jpeg",
  },
  {
    id: 4,
    region: "Langtang Region",
    country: "Nepal",
    duration: "7 days",
    title: "Langtang Valley Trek - 7 Days",
    difficulty: "Moderate",
    altitude: "5545",
    price: "1,200",
    reviews: 14,
    bannerMessage: "Booking Open for 2025",
    image: "/Images/package/everest-base-camp-trek.jpeg",
  },
  {
    id: 5,
    region: "Everest Region",
    country: "Nepal",
    duration: "13 days",
    title: "Everest Base Camp Trek - 13 Days",
    difficulty: "Moderate",
    altitude: "5555",
    price: "1,499",
    reviews: 14,
    bannerMessage: "Booking Open for 2025",
    image: "/Images/package/everest-base-camp-trek.jpeg",
  },
  {
    id: 6,
    region: "Annapurna Region",
    country: "Nepal",
    duration: "11 days",
    title: "Annapurna Base Camp Trek - 11 Days",
    difficulty: "Moderate",
    altitude: "4130",
    price: "800",
    reviews: 14,
    bannerMessage: "Booking Open for 2025",
    image: "/Images/package/everest-base-camp-trek.jpeg",
  },
  // {
  //   id: 7,
  //   region: "Annapurna Region",
  //   country: "Nepal",
  //   duration: "7 days",
  //   title: "Mardi Himal Trek - 7 Days",
  //   difficulty: "Moderate",
  //   altitude: "5545",
  //   price: "500",
  //   reviews: 14,
  //   bannerMessage: "Booking Open for 2025",
  //   image: "/Images/package/everest-base-camp-trek.jpeg",
  // },
  // {
  //   id: 8,
  //   region: "Langtang Region",
  //   country: "Nepal",
  //   duration: "7 days",
  //   title: "Langtang Valley Trek - 7 Days",
  //   difficulty: "Moderate",
  //   altitude: "5545",
  //   price: "1,200",
  //   reviews: 14,
  //   bannerMessage: "Booking Open for 2025",
  //   image: "/Images/package/everest-base-camp-trek.jpeg",
  // },
];

export const aboutusSectionFeatureData = [
  {
    icon: RiUserStarLine,
    title: "20 Years+ Experience",
  },
  {
    icon: FaTripadvisor,
    title: "800+ TripAdvisor Reviews",
  },
  {
    icon: RiMoneyDollarCircleLine,
    title: "Best Price Guaranteed",
  },
  {
    icon: RiMapPinLine,
    title: "More Than 300 Trips",
  },
];

export const departureDateData = [
  {
    id: 1,
    date: "2025-01-01 - 2025-01-15",
    tripName: "Everest Base Camp Trek - 13 Days",
    price: 1499,
  },
  {
    id: 2,
    date: "2025-02-15 - 2025-02-25",
    tripName: "Annapurna Base Camp Trek - 11 Days",
    price: 800,
  },
  {
    id: 3,
    date: "2025-03-10 - 2025-03-20",
    tripName: "Mardi Himal Trek - 7 Days",
    price: 500,
  },
  {
    id: 4,
    date: "2025-04-20 - 2025-04-30",
    tripName: "Langtang Valley Trek - 7 Days",
    price: 1200,
  },
  {
    id: 5,
    date: "2025-05-01 - 2025-05-10",
    tripName: "Annapurna Circuit Trek - 15 Days",
    price: 1500,
  },
];
